### ISSUE TITLE
How to return literals?

### ISSUE THREAD

**Issue by getify** [bakkot/do-expressions-v2#11]
The explainer shows returning the result of function calls (by simply calling them and relying on the completion value), as well as an expression (`tmp * tmp + 1`). But I'm wondering about the ergonomics of returning literal expressions, like strings, numbers, booleans, arrays, and (especially) objects.

```js
let fancyJobTitle = do {
   let title = getBoringJobTitle() || "Intern";
   `Sr. Rockstar ${title.toLowerCase()}`;
}
```

I assume that works. But it's not particularly readable/obvious that the string hanging out there is the result of the `do`. Similarly:

```js
let meaningOfLife = do {
   let answer = askComputer();
   if (answer !== undefined) answer;
   else false;
}
```

It doesn't seem terribly obvious that `false` might come out here. And also, implied `undefined` could be confusing here:

```js
let meaningOfLife = do {
   let answer = askComputer();
   if (answer !== undefined) answer;
}
```

Even more confusing to me is how do you express the returning of an object literal from such an expression. I assume we have to wrap in parens?

```js
let status = { step: 3 };
status = do {
   let { step = 1, phase = "beta", milestone = "q2" } = status;
   ({ step, phase, milestone });
}
```

(I think that one in particular could introduce an ASI hazard if the preceding statement doesn't have a terminating `;`, because then the `({ .. })` looks and is treated like a function call even though it's on the next line.)

----

To address these concerns, I have a soft proposal idea I wanted to float... that you should be allowed (but not required) to use an additional keyword token to disambiguate (and make more readable/obvious) the literal/expression you're intending to "return".

I was thinking something like metaprop keyword style:

* `return.do`
* `yield.do`
* `do.return`
* `do.yield`
* `do.ret`
* ...etc

So for example: 

```js
let status = { step: 3 };
status = do {
   let { step = 1, phase = "beta", milestone = "q2" } = status;
   do.yield { step, phase, milestone };
}
```

There we remove the need for the parens, we eliminate the ASI hazard from the previous line (though this new keyword would have its own ASI requirement), and we make it more obvious in places where it seems a little hidden/unobvious/ambiguous.

```js
let meaningOfLife = do {
   let answer = askComputer();
   if (answer !== undefined) return.do answer;
   else return.do false;
}
```

By making this keyword optional instead of required, it reduces the burden of the feature in cases where the keyword wouldn't be as helpful, but allows it in places where it is. It's sorta like how you can choose between either of these styles of arrow-functions according to your stylistic preferences:

```js
const fn1 = (x,y) => ({ x, y });
const fn2 = (x,y) => { return { x, y }; };
```

The choice to give arrow functions a "full non-concise body" option was a big one... which added a bit of complexity and cognitive overhead. I used to lament that, but 6 years on, I think that *choice* was a key design "feature" here, because it's made arrow functions more broadly applicable.

I think the same could be true of this optional keyword idea inside `do` expressions.

**Comment by bakkot** [comment]
Yeah, that's definitely a concern. Rust partially addresses this by omitting the trailing semicolon on the expression which gives the block its value, as in

```js
let fancyJobTitle = do {
   let title = getBoringJobTitle() || "Intern";
   `Sr. Rockstar ${title.toLowerCase()}`
};
```

While it would be a purely stylistic choice to do the same in JavaScript, I think it would be a useful convention to adopt.

I think Rust users have managed to learn what such blocks mean reasonably easily, and I'm hopeful JavaScript users would be able to do the same without adding any new keywords. I'm reluctant to introduce a new purely optional keyword: unlike with arrows, where allowing authors to omit `{ return _ }` let them be more concise, here the new optional form would be more verbose.

There's a rule of thumb I've heard cited as [Stroustroup's Rule](https://www.thefeedbackloop.xyz/stroustrups-rule-and-layering-over-time/), which says

> For new features, people insist on LOUD explicit syntax.
> For established features, people want terse notation.

My hope is that the current proposal is just enough new terse syntax that people will learn it without too much trouble and grow to prefer it over time as they become familiar with the feature. If that's so, having the optional keyword hanging out as an additional thing readers of the language would need to learn would be unfortunate.

---

> And also, implied `undefined` could be confusing here:

I'm probably going to drop support for if-without-else as the final statement of a `do`, which will avoid at least this particular risk of confusion.

**Comment by MaxGraey** [comment]
> I think Rust users have managed to learn what such blocks mean reasonably easily, and I'm hopeful JavaScript users would be able to do the same without adding any new keywords

Java 15 introduced expression-based pattern matching which use `yield` (similar to generators) instead `return` for returning from expression blocks

**Comment by getify** [comment]
my main intended use-case is the one I showed with the object literal... I call that pattern (without `do`-expressions but just with functions or IIFEs) "destructuring and restructuring", and I like to use it somewhat frequently. The need to use parens is pretty unfortunate IMO. That's what initially interested in me in adding the optional keyword marker so that parens aren't needed.

I'm also concerned about some of the implied ASI hazards, such as returning an array literal on its own line and that opening `[` instead being interpreted as part of the previous line's statement/expression.

**Comment by bakkot** [comment]
I've recreated this issue in the [main repo](https://github.com/tc39/proposal-do-expressions/issues/55), now that I am a maintainer of it. Apologies for the churn. Let's continue the discussion there.
