### ISSUE TITLE
The do-expression equivalent to eval(), or not?

### ISSUE THREAD

**Issue by aimingoo** [bakkot/do-expressions-v2#3]
For the case:
```javascript
let x = do {
  let tmp = f();
  tmp * tmp + 1
};
```

will equivalent to next:
```javascript
let x = eval(`
  let tmp = f();
  tmp * tmp + 1
`);
```

Is not it? So why do we need the do-expression?

**Comment by bakkot** [comment]
`eval` is bad (and [unavailable in many contexts](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)).
