### ISSUE TITLE
Spec bug: EndsInIterationOrDeclaration not be able to check this case

### ISSUE THREAD

**Issue by Jack-Works** [bakkot/do-expressions-v2#4]
I implemented `EndsInIterationOrDeclaration`, `isBreak` and `isEmpty` step-by-step but I found I cannot trigger the error in this case:

```js
const x = do {
    function y() {}
}
```

If the algorithm is correct, it will trigger an error like this:

![image](https://user-images.githubusercontent.com/5390719/105568548-4085cf00-5d75-11eb-80ac-18c9bad5e8a1.png)

But actually, no error is reported. Implementation URL: https://github.com/microsoft/TypeScript/pull/42437/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R31249

In debugging, I found the reason is that `isLast` is false in this case.

**Comment by bakkot** [comment]
Thanks for the report. I think this is a bug in your implementation, not the spec text: when it's invoked in the Early Error, _isLast_ is `true`:

> It is a Syntax Error if EndsInIterationOrDeclaration of Block with arguments « » and **true** is true.

Note the second argument there. (You should probably not give it default values for its parameters, since they don't have defaults in the spec.)

**Comment by Jack-Works** [comment]
Oh I thought `arguments « »` is the argument list so I ignored the following text, let me try it

**Comment by Jack-Works** [comment]
What about this case? What parameter should I call itwith?

```
SwitchStatement :
    switch ( Expression ) CaseBlock
        Return EndsInIterationOrDeclaration of CaseBlock.
```

**Comment by Jack-Works** [comment]
fixed in https://github.com/microsoft/TypeScript/pull/42437/commits/06c0c3de9d4ffacff3332f5711f80155bb8244d2

**Comment by bakkot** [comment]
> What about this case? What parameter should I call it with?

Ah, that's a bug, yes. You should use the same arguments it was called with, i.e. `labelSet` and `isLast`. Fixed in https://github.com/bakkot/do-expressions-v2/commit/278de093e19b8868907add40a770dd3841441ffb.
