### ISSUE TITLE
Current spec text doesn't disallow `break;` and `continue;` in do expressions

### ISSUE THREAD

**Issue by yume-chan** [bakkot/do-expressions-v2#6]
At https://bakkot.github.io/do-expressions-v2/#sec-doexpression-static-semantics-early-errors it reads:

> * It is a Syntax Error if ContainsUndefinedBreakTarget of Block with argument « » is **true**.

However, `ContainsUndefinedBreakTarget` doesn't return `true` for a `break;` statements.

At https://tc39.es/ecma262/#sec-static-semantics-containsundefinedbreaktarget it reads:

> _BreakStatement_ : **break ;**
>   1. Return **false**.

Disallowing `break;` across (only) function boundaries is defined at https://tc39.es/ecma262/#sec-break-statement-static-semantics-early-errors

> It is a Syntax Error if this BreakStatement is not nested, directly or indirectly (but not crossing function boundaries), within an _IterationStatement_ or a _SwitchStatement_.

Same for `continue;` statements.

So is it intentional to disallow `break label;` and `continue label;`, but allow `break;` and `continue;`?

**Comment by bakkot** [comment]
No, that's not intentional. Fixed in e3e306d.

(Incidentally I think that error should be better-specified. We _should_ just reuse the `ContainsUndefinedBreakTarget` machinery.)
