### ISSUE TITLE
do expressions can introduce strict mode

### ISSUE THREAD

**Issue by michaelficarra** [bakkot/do-expressions-v2#7]
From #tc39-delegates IRC:

> 14:48:41	michaelficarra	I kind of prefer it introducing a strict context actually
> 14:48:52	michaelficarra	it's a new feature, who would want to write sloppy code inside a new feature?
> 14:49:03	ljharb	yeah i kind of like that too
> 14:49:22	ljharb	historically the pushback to that is "refactoring hazard", but somehow that was fine for Modules and `class`
> 14:49:31	michaelficarra	yeah
> 14:49:36	ljharb	(ie, `async function`, generators, etc weren't auto-strict for that reason, iirc)
> 14:50:17	michaelficarra	that makes sense though since functions don't auto-introduce strict and they're just function variants
> 14:50:22	michaelficarra	this is a new kind of thing, like class
> 14:50:34	michaelficarra	totally fine for those to introduce strict mode
> 14:50:39	ljharb	fair
> 14:50:57	rkirsling	in a way, given that `async function` is a kind of `function` it makes sense that it would need to use `'use strict''` whereas `do {}`, like `class {}`, wouldn't have a directive _within_ it
> 14:51:11	michaelficarra	^ exactly
> 14:51:18	rkirsling	so I would agree with strict-only unless we can think of a way in which it is harmful

/cc @ljharb @rkirsling

**Comment by gibson042** [comment]
The intent of this proposal seems to be introduction of a new block in expression context with particular encouragement of author intuition that the braces "melt away" to some extent. Silently adding strictness inside that construct would be quite surprising.

**Comment by ljharb** [comment]
To be fair tho, new code is highly likely to be written in a Module or class or strict context, so the likelihood that a do expression would appear in a sloppy context is pretty low.

**Comment by bakkot** [comment]
I've recreated this issue in the [main repo](https://github.com/tc39/proposal-do-expressions/issues/56), now that I am a maintainer of it. Apologies for the churn. Let's continue the discussion there.

**Comment by Jack-Works** [comment]
@bakkot you can try to use the `transfer issue` feature to move the issue directly

**Comment by ljharb** [comment]
@Jack-Works that only works between repos in the same org.
