### ISSUE TITLE
Combine if / else / while with with "do" semantics as shorthands

### ISSUE THREAD

**Issue by MaxGraey** [bakkot/do-expressions-v2#8]
Instead
```js
let res = do {
  if (a > 0) { 1 } else { 2 }
}
```
what if use this as more compact version?
```js
let res = if (a > 0) do { 1 } else { 2 };
```
same for `while`, `for` and etc.
It also useful for future pattern matching which already expression:
```js
let res = case (a > 0) do {
  when true -> 1,
  when false -> 2
}
```
You can go further and make parentheses optional:
```js
let res = if a > 0 do { 1 } else { 2 };
```
or even more blockless (also optionally):
```js
let res = if a > 0 do 1 else 2;
```

**Comment by bakkot** [comment]
The form currently in this proposal is necessary to meet the use case of introducing expression-local variables, as in

```js
let x = do {
  let tmp = Math.random();
  tmp * tmp
};
```
Since this form is necessary anyway, and also allows you to put `if`/`else` (etc) statement position, I don't think this proposal ought to introduce any other new syntaxes such as the ones you suggest.

**Comment by MaxGraey** [comment]
The question is what if more frequent scenario for such expressions. 
Also what if we want use nested if / else expressions? Should we do this:
```ts
let res = do {
  if (a > 0) { 
    do { if (b == 0) { 1 } else { 2 } }
  } else {
    do { if (b == 0) { 3 } else { 4 } }
  }
}
```
or everything inside do block becomes expressions automatically?
Otherwise with this proposal it will be less verbose:
```js
let res = if a > 0 do { 
  if b == 0 do { 1 } else { 2 }
} else {
  if b == 0 do { 3 } else { 4 }
}
```

**Comment by bakkot** [comment]
> The question is what if more frequent scenario for such expressions.

I'm sorry, I don't understand the question.

> Also what if we want use nested if / else expressions?

You can just do that:

```js
let res = do {
  if (a > 0) { 
    if (b == 0) {
      1
    } else {
      2
    }
  } else {
    if (b == 0) {
      3
    } else {
      4
    }
  }
};
```

You don't need any additional `do`s.

**Comment by MaxGraey** [comment]
I see. Thanks!
